### ISSUE TITLE
WebUI白屏

### ISSUE THREAD

**Issue by zym013579** [powerAn2020/ZeroTierForKSU#28]
现象描述：刷入模块后打开WebUI无任何显示。
问题版本：试了一下Release中的版本，[1.14.0](https://github.com/powerAn2020/ZeroTierForKSU/releases/tag/1.14.0)可以正常显示，之后的版本都显示空白。
手机：小米13Ultra，HyperOS正式版1.0.16.0
KSU：11928，LKM模式

更早的版本（记不太清了，可能是[1.12.2](https://github.com/powerAn2020/ZeroTierForKSU/releases/tag/1.12.2)）也出现过类似的情况，当时清除KSU的数据后，第一次进入WebUI可以打开，之后也会白屏。这也可能是KSU的bug。

另外，同时在使用[Asterisk4Magisk/Xray4Magisk](https://github.com/Asterisk4Magisk/Xray4Magisk)，该模块的WebUI正常。

**Comment by powerAn2020** [comment]
白屏截图来个呗，我卸载模块清空kernelsu数据后重新安装模块并没有复现。

**Comment by zym013579** [comment]
> 白屏截图来个呗，我卸载模块清空kernelsu数据后重新安装模块并没有复现。

第一张图是模块页面，点了打开就是第二张图，等了一会儿也没有变化。模块的功能是正常的，只是UI不显示
![Screenshot_2024-10-09-18-04-06-262_me weishu kernelsu](https://github.com/user-attachments/assets/99c08288-6fae-453d-becc-24750717b552)
![Screenshot_2024-10-09-18-04-16-358_me weishu kernelsu](https://github.com/user-attachments/assets/331a5367-3999-4fdb-9a25-484adffd8ab5)

**Comment by powerAn2020** [comment]
升级webview组件或者安装chrome或者edge试一下，webui依赖webview组件，有可能是版本低有些特性不支持

**Comment by powerAn2020** [comment]
暂时先用下能用的版本吧，新版本只是加了zerotier 网络管理功能(先在zerotier官网管理)，只有需要折腾组网信息的时候才会用的，我在后面加一个日志输出功能，目前版本没日志收集功能。

**Comment by MNDIA** [comment]
White screen +1  test come from From apatch
The UI in the apatch manager is white
But we can enter UI through the io.github.a13e300.ksuwebui independent application

If it is a webview problem as author said, it means that the webview embedded in apatch is old

**Comment by zym013579** [comment]
> 升级webview组件或者安装chrome或者edge试一下，webui依赖webview组件，有可能是版本低有些特性不支持

试了一下当前的webview，版本是129.0.6668.81，卸载更新后版本是118.0.5993.80，都是白屏。
使用上面提到的ksuwebui可以正常进入页面。

**Comment by powerAn2020** [comment]
![Screenshot_2024-10-09-21-15-30-564_github.tornaco.android.thanos.pro.jpg](https://github.com/user-attachments/assets/0f0cbb72-a58f-4137-ad82-90ca4490f109)

![Screenshot_2024-10-09-21-15-42-351_github.tornaco.android.thanos.pro.jpg](https://github.com/user-attachments/assets/98ad90e0-776a-4210-b0eb-8c18b86e4239)

![Screenshot_2024-10-09-21-16-42-753_github.tornaco.android.thanos.pro.jpg](https://github.com/user-attachments/assets/72c4de7c-cfba-42c3-896e-a13112cea77c)

以上是我正常在用的版本，仅供参考。貌似在安装chrome的情况下会接管默认webview,目前信息有限也只是猜测是webview的问题。

**Comment by powerAn2020** [comment]
@zym013579 @MNDIA 版本的问题，当前版本的web api是有bug的，需要等ksu发新版，apatch代码是从ksu复制的所以是同一个问题。web api代码我已经通过补丁的形式提前修复了，但是app的只能等发新版，我是用的是ksu ci版。

**Comment by zym013579** [comment]
> @zym013579 @MNDIA 版本的问题，当前版本的web api是有bug的，需要等ksu发新版，apatch代码是从ksu复制的所以是同一个问题。web api代码我已经通过补丁的形式提前用上了，所以ksu独立版才能正常使用，暂时没有解决办法，只能等发新版，另外我是用的是[ksu ci版本](https://github.com/tiann/KernelSU/actions/runs/11090045931)

试了一下ci版，确实可以打开了

**Comment by RyanRaw** [comment]
> > @zym013579 @MNDIA 版本的问题，当前版本的web api是有bug的，需要等ksu发新版，apatch代码是从ksu复制的所以是同一个问题。web api代码我已经通过补丁的形式提前用上了，所以ksu独立版才能正常使用，暂时没有解决办法，只能等发新版，另外我是用的是[ksu ci版本](https://github.com/tiann/KernelSU/actions/runs/11090045931)
> 
> 试了一下ci版，确实可以打开了

能分享一下APK吗,我也遇到了同样的问题kernelSU 1.01-11928

**Comment by zym013579** [comment]
> > > @zym013579 @MNDIA 版本的问题，当前版本的web api是有bug的，需要等ksu发新版，apatch代码是从ksu复制的所以是同一个问题。web api代码我已经通过补丁的形式提前用上了，所以ksu独立版才能正常使用，暂时没有解决办法，只能等发新版，另外我是用的是[ksu ci版本](https://github.com/tiann/KernelSU/actions/runs/11090045931)
> > 
> > 
> > 试了一下ci版，确实可以打开了
> 
> 能分享一下APK吗,我也遇到了同样的问题kernelSU 1.01-11928

ksu已经更新了release，1.0.2

**Comment by RyanRaw** [comment]
> > > > @zym013579 @MNDIA 版本的问题，当前版本的web api是有bug的，需要等ksu发新版，apatch代码是从ksu复制的所以是同一个问题。web api代码我已经通过补丁的形式提前用上了，所以ksu独立版才能正常使用，暂时没有解决办法，只能等发新版，另外我是用的是[ksu ci版本](https://github.com/tiann/KernelSU/actions/runs/11090045931)
> > > 
> > > 
> > > 试了一下ci版，确实可以打开了
> > 
> > 
> > 能分享一下APK吗,我也遇到了同样的问题kernelSU 1.01-11928
> 
> ksu已经更新了release，1.0.2

设备不是GKI的,更到1.02连模块都没了.

**Comment by RyanRaw** [comment]
> @RyanRaw [5ec1cff/KsuWebUIStandalone](https://github.com/5ec1cff/KsuWebUIStandalone)要不试试独立面板？按理说只更新kernelsu管理器没关系的啊。

非GKI设备不能更新到1.0.2,那边已经 有人提issues了.

**Comment by RyanRaw** [comment]
> @RyanRaw [5ec1cff/KsuWebUIStandalone](https://github.com/5ec1cff/KsuWebUIStandalone)要不试试独立面板？按理说只更新kernelsu管理器没关系的啊。

这个独立面板可以用,非常感谢.

**Comment by eritpchy** [comment]
apatch 12.5号构建的版本依然白屏，sad, 浏览器内核也更新了毫无效果

**Comment by powerAn2020** [comment]
@eritpchy 可以给下ci版地址吗，我瞅瞅源码看看

**Comment by eritpchy** [comment]
> @eritpchy 可以给下ci版地址吗，我瞅瞅源码看看

https://github.com/bmax121/APatch/actions/runs/12181525422

目前我的环境是ColorOS 15.0 Apatch 11.1(11015)  浏览器内核131.0 有装Chrome浏览器

昨晚又试了下上面说的14.0老版本包括清数据， 一进去首页可以显示，提示服务未启动，点启动就白屏了最新版是一进去就白屏，独立版KsuWebUI表现一致。

**Comment by powerAn2020** [comment]
> apatch 12.5号构建的版本依然白屏，sad, 浏览器内核也更新了毫无效果

@eritpchy 额，我看了下，apatch最新代码中webuiapi还是没和ksu同步😅[Apatch代码](https://github.com/bmax121/APatch/blob/main/app/src/main/java/me/bmax/apatch/ui/webui/WebViewInterface.kt) - [KernelSU代码](https://github.com/tiann/KernelSU/blob/main/manager/app/src/main/java/me/weishu/kernelsu/ui/webui/WebViewInterface.kt)
你试下这个，将解压的所有文件覆盖到/data/adb/modules/ZeroTierForKSU/webroot/下然后再试试。
[dist.zip](https://github.com/user-attachments/files/18032226/dist.zip)

**Comment by eritpchy** [comment]
> 包括清数据， 一进去首页可以显示，提示服务未启动，点启动就白屏

覆盖dist.zip可以了， 不过要清数据， 不然第一次的表现是显示未启动， 点击启动就白屏了， 除了清数据怎么搞一进去都是白屏.

诶我发现居然要token..我好像记得很老的版本好像是不用的， 期望以后可以有不用token的

**Comment by powerAn2020** [comment]
> > 包括清数据， 一进去首页可以显示，提示服务未启动，点启动就白屏
> 
> 覆盖dist.zip可以了， 不过要清数据， 不然第一次的表现是显示未启动， 点击启动就白屏了， 除了清数据怎么搞一进去都是白屏.
> 
> 诶我发现居然要token..我好像记得很老的版本好像是不用的， 期望以后可以有不用token的

这个token是zerotier官方api的，你不填写只是不能管理网络而已，不影响本地服务的，而且这个是只能官网生成，我也没法提供啊😂
